### ISSUE TITLE
AWS G4dn.xLarge stuck at 1366 x 768

### ISSUE THREAD

**Issue by dollars0427** [jamesstringerparsec/Parsec-Cloud-Preparation-Tool#18]
Hello, 
Recently I try to using AWS G4dn.xLarge to create my cloud computer. However, after I install everything and update GPU driver, I found that the resolution is stuck at 1366x768. 

I know GCP can enable GRID Virtual Workstation to fix this problem, but AWS do not had this option. Should I using Nvdia AMI to fix this problem ?

Thank you.

**Comment by jamesstringerparsec** [comment]
Did the script request you enter access key and security key information? Did it show any red error messages?

**Comment by dollars0427** [comment]
Yes, the script need to enter access key and security key, but it do now show any red error message.
However, when I installed GPU driver(Using GPU Update Tool), then run the tool again, it still told me to update the GPU driver:
```bash
Checked Now 03/04/2020 02:32:10 - An update is available ( > grid)
Update now? - (!) Machine will automatically reboot if required (!)
(Y/N):
```
After I update the driver, this message still do not disappear, and the resolution stuck at 1366x768 too.

First Install:
![螢幕截圖 2020-03-04 上午10 33 11](https://user-images.githubusercontent.com/2662715/75839838-ba7f3380-5e04-11ea-807d-4e1e37c04a45.jpg)

Installed, than update again:
![螢幕截圖 2020-03-04 上午10 45 52](https://user-images.githubusercontent.com/2662715/75840051-55780d80-5e05-11ea-91b1-dc2e67e56a4f.png)


![螢幕截圖 2020-03-04 上午10 58 16](https://user-images.githubusercontent.com/2662715/75840832-219de780-5e07-11ea-9772-2d8fc3c76b27.png)

**Comment by jamesstringerparsec** [comment]
Thank you for the information, it seems AWS has changed something on their end again.  I will have to resolve it.  It's not the scripts fault unfortunatly, but more Amazon keeps changing how they store drivers for the G4.

**Comment by dollars0427** [comment]
Thank you very much. I try to follow the guide on AWS Support (https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html), then install the driver without script,
but it's still cannot solve the problem -- So I think there are something wrong with AWS too ;)

**Comment by jamesstringerparsec** [comment]
I just created a G4.dn instance and uses GPU updater to install the driver...After a reboot I was able to select 4K resolution.  Are you creating your instance from a base Server 2016 / Server 2019 image? Or an AMI?

**Comment by dollars0427** [comment]
> I just created a G4.dn instance and uses GPU updater to install the driver...After a reboot I was able to select 4K resolution. Are you creating your instance from a base Server 2016 / Server 2019 image? Or an AMI?

I creating my instance from base Server 2016 image (Which provided by AWS). Can I ask which region are you using? I think maybe there are some problem in Hong Kong region... ;)

**Comment by jamesstringerparsec** [comment]
I'm using US-East-1

**Comment by dollars0427** [comment]
I confirmed there are some problem in Hong Kong region -- I can select 4K resolution when I using US-East-1 and ap-southeast-1 region, only Hong Kong region cannot made it.
Thank you very much. ;)

**Comment by peterkilfeather** [comment]
I also have this problem when setting up this EC2 instance on EU-west-2.

**Comment by kuges** [comment]
Confirming I'm currently having the same issue in AP-Southeast-2

**Comment by caasig** [comment]
Same with ap-southeast-1. It seems the issue may actually lie with the "latest" nvidia driver, specifically 442.59 which this tool and the aws docs tries to install. I did manage to get it working by manually installing 442.19

**Comment by dollars0427** [comment]
> Same with ap-southeast-1. It seems the issue may actually lie with the "latest" nvidia driver, specifically 442.59 which this tool and the aws docs tries to install. I did manage to get it working by manually installing 442.19

Thank you ! This workaround is great.   It look like "Lastest" nvidia driver can not work on these region's server.

**Comment by jamesstringerparsec** [comment]
Will you guys please contact AWS and tell them that their driver doesn't work?

**Comment by dollars0427** [comment]
> Will you guys please contact AWS and tell them that their driver doesn't work?
> 
> If all of you do it individually hopefully this will increase the changes of this being fixed quickly.
> 
> From what I can tell, nothing in the process of adding the cert to the machine and changing the registry has changed...so this must be down to the driver itself, or the cert they're providing being invalid.
> 
> Essentially all this script does is follow the AWS documentation to install the driver per their instructions.

I want to contact AWS to tell them this problem, but their free customer support look like can not support technical issues. Are there any method for contact with AWS ?

**Comment by kuges** [comment]
I already had an open support ticket with AWS re. this issue and have just asked for a bug to be raised for the driver.

**Comment by jamesstringerparsec** [comment]
> I already had an open support ticket with AWS re. this issue and have just asked for a bug to be raised for the driver.

Legend, thanks!

**Comment by nateberkopec** [comment]
Thanks for doing that. Should we change the script to install 442.19 in the meantime, as a fix could be a long time coming?

**Comment by jamesstringerparsec** [comment]
> Thanks for doing that. Should we change the script to install 442.19 in the meantime, as a fix could be a long time coming?

I recommend manually installing the 442.19 driver if you know how to navigate S3, I'm very hesitant to keep updating the script every time AWS drops the ball.  This is the 3rd time there has been an issue with g4dn updates due to them changing / breaking things.  The long solution here is to get AWS to fix the issue / update their documentation and stick with it.

**Comment by kuges** [comment]
I seem to be having another, possibly related issue. I can't:

a) set a custom resolution (so can't get my monitor resolution of 3440 x 1440)
b) changing the resolution in the NVidia Control Panel actually does nothing at all. The only way to change resolution is via Windows Display Settings.

**Comment by dollars0427** [comment]
> I seem to be having another, possibly related issue. I can't:
> 
> a) set a custom resolution (so can't get my monitor resolution of 3440 x 1440)
> b) changing the resolution in the NVidia Control Panel actually does nothing at all. The only way to change resolution is via Windows Display Settings.

I think it is related issues. I never change my resolution successfully when using G4dn.xlarge in Hong Kong region too.
Can you change the resolution after using @caasig 's workaround?

**Comment by GazEdge** [comment]
What about using [NVIDIA Gaming PC - Windows Server 2016](https://aws.amazon.com/marketplace/pp/B07SRJGXWZ?qid=1585257245484&sr=0-2&ref_=srh_res_product_title) it has the 442.19 already installed. Ill give it a try shortly.

**Comment by kuges** [comment]
> I think it is related issues. I never change my resolution successfully when using G4dn.xlarge in Hong Kong region too.
> Can you change the resolution after using @caasig 's workaround?

Nope, running v442.19 but issue remains.

**Comment by dollars0427** [comment]
> What about using [NVIDIA Gaming PC - Windows Server 2016](https://aws.amazon.com/marketplace/pp/B07SRJGXWZ?qid=1585257245484&sr=0-2&ref_=srh_res_product_title) it has the 442.19 already installed. Ill give it a try shortly.

I tried this AMI before create this issues, but it do not work as cannot find the Windows password :(

**Comment by dollars0427** [comment]
> > I think it is related issues. I never change my resolution successfully when using G4dn.xlarge in Hong Kong region too.
> > Can you change the resolution after using @caasig 's workaround?
> 
> Nope, running v442.19 but issue remains.

Understand. So it look like this bug should be fixed by AWS or NVDIA too :(

**Comment by GazEdge** [comment]
> What about using [NVIDIA Gaming PC - Windows Server 2016](https://aws.amazon.com/marketplace/pp/B07SRJGXWZ?qid=1585257245484&sr=0-2&ref_=srh_res_product_title) it has the 442.19 already installed. Ill give it a try shortly.

Works fine in eu-west-1, g4dn.xlarge, variety of resolutions now available including 1080 and 4k

**Comment by nateberkopec** [comment]
I'm confused on how there's a region-specific component to this. Shouldn't the 442.19 driver be the same regardless of what region you're in?

**Comment by Marcel-G** [comment]
I noticed a new driver added to the s3 bucket last night (442.49). I tried it and it solved this issue for me.
Windows Server 2016, eu-central-1

The driver is [442.49_grid_win10_64bit_international.exe](https://ec2-windows-nvidia-drivers.s3.us-east-1.amazonaws.com/g4/latest/442.49_grid_win10_64bit_international.exe)

**Comment by GazEdge** [comment]
> I noticed a new driver added to the s3 bucket last night (442.49). I tried it and it solved this issue for me.
> Windows Server 2016, g4dn.xlarge, eu-central-1
> 
> The driver is [442.49_grid_win10_64bit_international.exe](https://ec2-windows-nvidia-drivers.s3.us-east-1.amazonaws.com/g4/latest/442.49_grid_win10_64bit_international.exe)

Thanks for letting us know, but as far as I can tell, this doesnt fix the issue when using GPU Updater. I've just run it again today g4dn.xlarge, eu-west-1, and its still using the AWS latest driver 442.59, which is the driver thats causing all the problems. So i consider this still something AWS need to fix.

**Comment by kuges** [comment]
Can confirm 442.49 fixed my issue with not being able to change resolutions in Nvidia Control Panel although still can't set a custom resolution. Also continues to work in being able to set a resolution over the previously stuck 1366 x 768.

**Comment by jamesstringerparsec** [comment]
The 442.49 driver is not in the `nvidia-gaming` S3 bucket, but `ec2-windows-nvidia-drivers` which seems now to support G4 instances as well as G3.  It's not a Gaming driver, but a Quadro driver.

**Comment by kuges** [comment]
> The 442.49 driver is not in the `nvidia-gaming` S3 bucket, but `ec2-windows-nvidia-drivers` which seems now to support G4 instances as well as G3. It's not a Gaming driver, but a Quadro driver. Previously you could only find G4 drivers in the `nvidia-gaming` s3 bucket

Is there any difference performance wise between the gaming driver and Quadro driver?

**Comment by niazmsameer** [comment]
I am having the same issue with a g4dn.xlarge instance in Hong Kong region (ap-east-1b)

**Comment by mihai9112** [comment]
Installing 442.49 on g4dn.xlarge in eu-west-2 fixed it. I can now run 4k resolution

**Comment by SimonHausdorf** [comment]
Resolution problem is solved for me too with 442.49

**Comment by Sam-Kruglov** [comment]
> I noticed a new driver added to the s3 bucket last night (442.49). I tried it and it solved this issue for me.
> Windows Server 2016, g4dn.xlarge, eu-central-1
> 
> The driver is [442.49_grid_win10_64bit_international.exe](https://ec2-windows-nvidia-drivers.s3.us-east-1.amazonaws.com/g4/latest/442.49_grid_win10_64bit_international.exe)

Thanks!
<img width="1318" alt="Screenshot 2020-04-09 at 00 46 27" src="https://user-images.githubusercontent.com/23556336/78836934-bd6cd580-79fb-11ea-9011-73f938065ae2.png">

**Comment by iovis** [comment]
> Installing 442.49 on g4dn.xlarge in eu-west-2 fixed it. I can now run 4k resolution

**Comment by Sam-Kruglov** [comment]
I have a public AMI that works, feel free to try it `ami-0f9eca13053241337`

**Comment by kabadisha** [comment]
Hey Guys,
I also had this issue and the 442.49 driver install fixed it for me. Thanks guys, and thanks to the maintainer(s) of this awesome script!

**Region:** eu-west-2 (London)
**Instance Type:** g4dn.xlarge
**OS:** Windows Server 2019

**Comment by jamesstringerparsec** [comment]
Folks, if you want this issue to be resolved for everyone else, you will need to contribute to this work by contacting Amazon support, and telling them their driver is not licensed for the latest windows nvidia-gaming driver.  Your help would be appreciated in helping to close this github issue.

**Comment by kabadisha** [comment]
Hi @jamesstringerparsec 

Happy to do so, however for the sake of us n00bs here, I will suggest how I would describe it to AWS support and maybe you can confirm I haven't got any wires crossed?

> Hi Support,
>It looks like there is an issue with the current nVidia drivers for the g4dn.xlarge instances using the T4 GPU in some regions. nVidia gaming driver version 442.59 is not licenced and so resolution choices are very limited with this driver installed. Installing version 442.49 (available here: https://ec2-windows-nvidia-drivers.s3.us-east-1.amazonaws.com/g4/latest/442.49_grid_win10_64bit_international.exe) fixed the issue.
>
>Region: eu-west-2 (London)
>Instance Type: g4dn.xlarge
>OS: Windows Server 2019

The only thing I want to add is a 'steps to reproduce' section, but I don't really know how they can reproduce the issue without installing and using Parsec - When I was having this issue, it wasn't restricting my resolutions when connected via RDP.

Suggestions welcome.
Cheers

**Comment by jamesstringerparsec** [comment]
Hey Charles

My script just follows the instructions provided by the AWS support page.

Instructions to reproduce are located in Step 4 on this support page. 
[Option 4: NVIDIA Gaming Drivers (G4 Instances)](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html)

After following those instructions, the 442.59 driver, located in the nvidia-gaming.s3.amazonaws.com/windows/latest bucket is not licensed and does not allow resolution choices when correctly following setup instructions.  

The working driver you're using now (442.49), is listed under "Option 3: GRID Drivers (G3 and G4 Instances)" and is a Quadro driver.

**Comment by kabadisha** [comment]
Sigh @jamesstringerparsec 

I only have basic support, which apparently isn't enough to report a bug. I went to the Dev forums to post an issue there, but as it's my first visit there my account is too fresh to post yet #rageface

I will try to post a bit later once my account has matured slightly. In the meantime, I have added feedback via the feedback link at the bottom of that docs page.

**Comment by orlyandico** [comment]
I've escalated this issue internally, will comment here again once there's an update.

**Comment by jamesstringerparsec** [comment]
@orlyandico Hello, are you an employee of AWS? If so, thank you.

**Comment by orlyandico** [comment]
Yup. Been working with Benjy.

**Comment by albertostefanelli** [comment]
I am not sure my problem is related to the same issue reported here but using GPU Update Tool after having run the preparation tool did not properly configure the graphic drivers. 

The GPU Update Tool displayed some error during the installation but successfully rebooted the system. Unfortunately, the drivers were not installed.

Install the driver manually does not solve the problem. I am running AWS G4dn.xLarge in London


<img width="1440" alt="Screenshot 2020-04-17 at 22 52 28" src="https://user-images.githubusercontent.com/41782142/79613770-75d30180-80ff-11ea-874f-feda188f207b.png">

<img width="1440" alt="Screenshot 2020-04-17 at 22 52 48" src="https://user-images.githubusercontent.com/41782142/79613764-71a6e400-80ff-11ea-9a84-0d778ef36955.png">

**Comment by dollars0427** [comment]
> I am not sure my problem is related to the same issue reported here but using GPU Update Tool after having run the preparation tool did not properly configure the graphic drivers.
> 
> The GPU Update Tool displayed some error during the installation but successfully rebooted the system. Unfortunately, the drivers were not installed.
> 
> Install the driver manually does not solve the problem. I am running AWS G4dn.xLarge in London
> 
> <img alt="Screenshot 2020-04-17 at 22 52 28" width="1440" src="https://user-images.githubusercontent.com/41782142/79613770-75d30180-80ff-11ea-874f-feda188f207b.png">
> 
> <img alt="Screenshot 2020-04-17 at 22 52 48" width="1440" src="https://user-images.githubusercontent.com/41782142/79613764-71a6e400-80ff-11ea-9a84-0d778ef36955.png">

Hi Alberto,
Can you provide the error message which displayed by GPU Update Tool ? Maybe it can help to find the problem.

**Comment by rdonadono** [comment]
I think it's the same error

![Schermata 2020-04-22 alle 14 13 31](https://user-images.githubusercontent.com/323353/79980544-90143300-84a3-11ea-9c82-0cb07ca5d82b.png)

**Comment by jamesstringerparsec** [comment]
This issue is solved

Copy all text from https://raw.githubusercontent.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool/master/PostInstall/PostInstall.ps1
Open %appdata%\ParsecLoader\GPU Updater Tool.ps1 in Notepad, replace all text in the document with the text you copied from Step 1.
Save the file (do not Save As)
Run GPU updater tool on the desktop

**Comment by Thiago-br** [comment]
> This issue is solved
> 
> Copy all text from https://raw.githubusercontent.com/jamesstringerparsec/Parsec-Cloud-Preparation-Tool/master/PostInstall/PostInstall.ps1
> Open %appdata%\ParsecLoader\GPU Updater Tool.ps1 in Notepad, replace all text in the document with the text you copied from Step 1.
> Save the file (do not Save As)
> Run GPU updater tool on the desktop

unfortunately didn't work for me =/

**Comment by Thiago-br** [comment]
It didn't work. Every time I initialize an instance I got stuck in 1366 x 768

**Comment by jamesstringerparsec** [comment]
> It didn't work. Every time I initialize an instance I got stuck in 1366 x 768

I updated my comment

**Comment by royaldallas** [comment]
Hey! I'm facing a similar issue. I'm using g4dn.xlarge spot requests and when I launch a new instance then run this script, I can get everything working and select from higher resolutions.

However, when I create an AMI from this instance, and then spin up an instance from that new AMI, the resolution is again limited to 1366 x 768. Any ideas? I'm in us-east-2 by the way.

Thanks in advance. :)

**Comment by Sam-Kruglov** [comment]
@royaldallas set everything up on the on-demand instance and take ami from there. To guarantee image integrity it needs to be able to reboot which it can't on spot instances

**Comment by Sarets** [comment]
Hello. I have same issue as @royaldallas . @Sam-Kruglov  I made AMI from on-demand instance which supports high resolution. But i get resolution 1366x768 when i create new instance based on the AMI i made.

> This issue is solved
> 
> Copy all text from https://raw.githubusercontent.com/jamesstringerparsec/Cloud-GPU-Updater/master/GPUUpdaterTool.ps1
> Open %appdata%\ParsecLoader\GPU Updater Tool.ps1 in Notepad, replace all text in the document with the text you copied from Step 1.

Also it doesn't help.

> Installing version 442.49 (available here: https://ec2-windows-nvidia-drivers.s3.us-east-1.amazonaws.com/g4/latest/442.49_grid_win10_64bit_international.exe) fixed the issue.

And this one.

Other thing is If i connect via RDP and via Parsec at the same time I got 1920x1080. 


My region is ap-southeast-1 (Singapore),  g4dn.xlarge, Windows Server 2016. 

May you give me any tips how to fix it? Thank you.

**Comment by Sam-Kruglov** [comment]
I had the same issue when I captured AMI from a spot instance and checked the "no reboot" checkbox. After that I created raw windows server 2019 on an on-deman instance, ran this tool, installed the games, and captured the AMI. After that it works every time I spawn a spot instance with my launch template

**Comment by Sarets** [comment]
@Sam-Kruglov Before I made snapshot from terminated instance and then created AMI from the snapshot. 
So, I do AMI based from working instance and I changed Windows from 2016 to 2019 Server. 

Also i can see that new instances from my current AMI creates in different area as before. Before it was ap-southeast-1a  instead ap-southeast-1b now. 

Now everything is working perfectly, 1920x1080 as i wished. Thank you very much for your help!

**Comment by royaldallas** [comment]
@Sam-Kruglov @Sarets Thanks for the reply. I tried creating an AMI from an on-demand instance in us-east-2 after running this script, and when I launch spot instances from that AMI, it still gives me the 1366 x 768 resolution. 

Did you guys do anything other than run the basic script? Did you try any of the things in these comments?

Any other suggestions?

Thanks again!

**Comment by royaldallas** [comment]
Also what drivers and region were you guys in?

**Comment by Sam-Kruglov** [comment]
@royaldallas 
![cover2](https://user-images.githubusercontent.com/23556336/81471953-90c7fb80-91fd-11ea-8035-a5d123ff447b.jpg)

**Comment by Sam-Kruglov** [comment]
@royaldallas actually today wanted to make a small change to my AMI and got the same issue. I think it might be related to the fact that new AMI builds from the closes EBS snapshots. Try to delete all EBS snapshots related to the instance you're taking AMI from so that the snapshot goes from zero to full.

**Comment by royaldallas** [comment]
@Sam-Kruglov were you able to fix it? It looks like my instances from the same AMI have the correct resolution in one availability zone, but not others. So I'm not sure if it's the AMI or an issue on Amazon's end.

**Comment by Sarets** [comment]
Hello @royaldallas
I did everything according this instruction https://github.com/keithvassallomt/parsec-aws-automation
Except any automation scripts and i did win server 2019 instead 2016. 
And important thing, i do AMI image from "started"(not "terminated") instance directly. I mean right click on instance then create image. In this case when i launch instance from AMI - it starts in the same zone as initial instance.

**Comment by ericzinnikas** [comment]
Another data point, I set up a brand new g4dn.2xlarge instance (worked fine). Then created an AMI for it, spun up and down 2x instances from that AMI and both worked fine. Then today I stood up an instance from that same AMI and was stuck at 1366x768. I'm confused why the behavior would change with the same AMI!

**Comment by KKostya** [comment]
Same for me. Creatin an instance from AMI image. Stuck at 1366x768. Tried GPUUpdaterTool with no luck.

**Comment by jamesstringerparsec** [comment]
You guys need to `route print` in cmd prompt and remove any static routes if they are present.

**Comment by ericzinnikas** [comment]
I can confirm with `route -p delete ip.addr.here` for all of the persistant ipv4 routes and a reboot later and I'm back to 1080p.

**Comment by KKostya** [comment]
Yep. Worked. Thank you, @jamesstringerparsec

**Comment by TTimo** [comment]
The script reports `Your PC already has the latest NVIDIA GPU Driver (443.18) available from nvidia.com` and stops.

But NVIDIA Control Panel reports 445.87 and the resolution is limited to 1366x768 still (g4dn.xlarge us-east-2a, this is from the NVidia AMI).

Even more strange, some of my systems do not have the problem and never needed the script to begin with, and offer the higher resolutions.

**Comment by nateberkopec** [comment]
@TTimo The README isn't really explicit about it, but I believe this tool is designed to be used with the Windows server AMIs, not the Nvidia ones.

**Comment by TTimo** [comment]
If I'm starting two instances, one on `us-east-2a` and one on `us-east-2c`, the `-2a` one reports `GRID Virtual Applications` in `nvidia-smi.exe`, the resolution is limited, and I can't find a way to fix it. The `-2c` however reports `GRID vGaming` and the higher resolutions are available.

This looks like an AWS problem to me. We have repeatedly created instances in `-2c` that are are fine, and created instances in `-2a` that are broken, coming out of the same AMI.

**Comment by jamesstringerparsec** [comment]
@TTimo Please read my comment from May 20th.

**Comment by TTimo** [comment]
@jamesstringerparsec dangit! I understand your comment now.

`nvidia-smi` reports `License Status              : Licensed` - but the VM is actually silently failing in some way. That's just nasty :(

**Comment by Sarets** [comment]
I faced same issue as [before](https://github.com/parsec-cloud/Parsec-Cloud-Preparation-Tool/issues/18#issuecomment-625206067) today. Amazon created instance from fine AMI in wrong location ap-southeast-1b, which always affect video settings and geting stuck resolution. I found that seems like possible to choose right "Availability zone" in process of creating instance from AMI. On "Step 3: Configure Instance Details" i checked "Request Spot instances" and then in parameter "Subnet" i choosed subnet from right location, in my case ap-southeast-1a. But maybe it was luck, i don't know. I hope so it will help somebody.

**Comment by jolian88** [comment]
Hey, I can report that I had the same exact issue: I had followed @keithvassallomt's excellent guide in  https://github.com/keithvassallomt/parsec-aws-automation, and I could have sworn everything was working fine up until recently when my same exact AMI image started to spin up instances that would refuse to go above 1366x768 or 1280x1024.
I tried GPU Updater and messing around with forcing resolution, but to no avail.

What actually worked for me was the below, thanks @jamesstringerparsec! I removed all 169.254.169.* persistent routes and voila, the driver magically licences itself (don't even need to reboot) and I can immediately change to 1920x1080 again!

I'm running a **g4dn.xlarge** spot instance in **eu-central-1a**, with the **445.87** driver.

What is weird is where these routes come from (I suppose "Sets persistent static routes to reach the metadata service and KMS servers." from https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/ec2launch.html, and whether removing them affects the Windows licencing? 🤔 - I did happen to see the "Activate Windows" background in another session when I removed the same set of persistent routes. But I don't really mind that as long as the Nvidia driver works properly! 😁

> You guys need to `route print` in cmd prompt and remove any static/persistant routes if they are present. There is no way the driver will get licensed if it can't talk to Amazon, which it won't be able to do if there are static routes set up by the original machine creation, which are invalid for the AMI you created.

**Comment by jamesstringerparsec** [comment]
The code has been once again updated to support AWS G4DN

Copy all text from https://raw.githubusercontent.com/jamesstringerparsec/Cloud-GPU-Updater/master/GPUUpdaterTool.ps1
Open %appdata%\ParsecLoader\GPU Updater Tool.ps1 in Notepad, replace all text in the document with the text you copied from Step 1.
Save the file (do not Save As)
Run GPU updater tool on the desktop

**Comment by Buzzpod** [comment]
@jamesstringerparsec Your ongoing support on this issue has been amazing. One extra question...does your latest script update (above) automatically delete all persistant ipv4 routes or does that still need to be donw manually? 
(the persistant route thing is what was causing the issue for me)

**Comment by jamesstringerparsec** [comment]
@Buzzpod You need to do it yourself as I don't know what else deleting those persistent routes does, perhaps it also stops your copy of Windows being licensed, or things of that nature.  I don't know.

**Comment by DolderM** [comment]
> 
> 
> You guys need to `route print` in cmd prompt and remove any static/persistant routes if they are present. There is no way the driver will get licensed if it can't talk to Amazon, which it won't be able to do if there are static routes set up by the original machine creation, which are invalid for the AMI you created.

Thank you.

**Comment by clovisd** [comment]
I'm getting the what appears to be essentially the same issue as described above using the latest Windows Server 2019 Base image from AWS. All this was done in AWS West-2 (Oregon) on a `NVIDIA RTX Virtual Workstation - WinServer 2019-vGPU` with a `g4dn.xlarge` instance.

Created the instance in AWS, then ran the ps1 Parsec Prep tool and can't get anything above 1366 x 768. 
![image](https://user-images.githubusercontent.com/1336589/128197054-107bc031-2d29-4352-bfe1-24c68820a98f.png)

I've run the GPU Updater tool and have the latest available 466.47 Driver version.

**Comment by keithvassallomt** [comment]
The way I'm solving it these days on new installs is to follow Option 4 from the following [guide](https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html#nvidia-gaming-driver) . It seems to be changes that AWS constantly make on their end and the script can't keep up.

**Comment by clovisd** [comment]
So a manual install didn't fix it either. The latest version available from the BitBucket is identical to the one the GPU Updated powershell script grabbed and installed.

At this point, I assume this might just be a problem with this version (`466.47`) that might be restricting Display resolutions rather than the tool or setup. 🤔

![image](https://user-images.githubusercontent.com/1336589/128204601-3297e55d-d8ca-4b75-9a8e-630cef99dc1b.png)

**Comment by TTimo** [comment]
The static routes fixed described in the comments above should still work.

**Comment by matusnovak** [comment]
I have tried this with Windows Server 2022 and `g4dn.xlarge` (the drivers have been installed manually as per AWS documentation). Resolution is stuck and can not be changed even after the reboot. No static routes present.

I have also tried Windows Server 2019 but I do not see any static routes, and the resolution is still stuck.

I have also tried Nvidia provided AMI (the Gaming one) for Windows Server 2019 but that one does not start the RDP server so there is no way to connect to it.

The AWS `g4dn` has a very bad user experience.
